FROM node

# Create app directory
WORKDIR /usr/src/api

# Install app dependencies
COPY node-3tier-app/api/ .
# fix resolv.conf against local reconfiguration
RUN echo "nameserver 8.8.8.8">/etc/resolv.conf && npm install && npm audit fix

CMD [ "npm", "start" ]